<a href="https://colab.research.google.com/github/PeriBerba/Linear-Algebra-LAB-activity/blob/main/LinAlg_Lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CpE
## Laboratory 4 : Vector Operations

Now that you have a fundamental knowledge about linear combination, we'll try to apply the fundamental operations

### Objectives
At the end of this activity you will be able to:
1. Referesh knowledge on vector operations while being familiar with new operations such as products.
2. Visualize vector operations.
3. Perform vector operations using Python.

## Discussion

In [ ]:
import numpy as np

We have dealt with some of the vector operations in the last module, now we will dwell into more operations. In this laboratory, we will tackle addition,multiplication,division and the inner product of a vector.

## Vector Addition

We have encountered vector before especially with your last activity. Vector addition is simply the element-wise addition of the scalar values of the vectors. Let's take the following vectors as a sample:

$$A = \begin{bmatrix}1\\2\\0\end{bmatrix}, B= \begin{bmatrix}3\\1\\-2 \end{bmatrix}$$

So if do a vector addition of these two vectors we'll get:

$$A + B = \begin{bmatrix}4\\3\\-2\end{bmatrix}$$

We can progammatically solve this using `np.add()` or simply using `+`.

In [ ]:
A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

In [ ]:
A+B+C

array([ 4,  3, -1])

In [ ]:
np.add(A,np.add(B,C))

array([ 4,  3, -1])

In [ ]:
np.sum(B)

2

## Vector Subtraction

Vector subtraction is similar to your vector addition but you would need to scale the second vector using a negative scalar that is usuall $-1$. So if we subtract vector $B$ from vector $A$ we get:

$$A-B = \begin{bmatrix}-2\\1\\2\end{bmatrix}$$

In Python, this can be achieved by using `np.subtract()` or `-`

In [ ]:
np.subtract(A,B)

array([-2,  1,  2])

In [ ]:
A-B

array([-2,  1,  2])

## Vector Multiplication

Vector multiplication, like addition does its operations element-wise. So basic vector multiplication can be achieved by multiplying the elements or the scalars of the vectors individually. So:
$$A * B = \begin{bmatrix}3\\2\\0\end{bmatrix}$$
We can implement this in code by using `np.multiply()` or simply operating with `*`.

In [ ]:
np.multiply(A,B)

array([3, 2, 0])

In [ ]:
A*B

array([3, 2, 0])

## Vector Division

Dividing a vector by another is uncommon, but if the situation specifies that each elements or scalars of the vector would be divided individually we can perform this by:
$$A./B = \begin{bmatrix}\frac{1}{3}\\2\\0\end{bmatrix}$$
Take note that the notation we used here is $./$ for element-wise division, this notation is based in a MATLab notation for element-wise division. This can be achieved in Python using `np.divide()` or `/`.

In [ ]:
np.divide(A,B)

array([ 0.33333333,  2.        , -0.        ])

In [ ]:
A/B

array([ 0.33333333,  2.        , -0.        ])

In [ ]:
C = np.array([3.9,1.8,7.7])
D = np.array([1,1,1])
C//D

array([3., 1., 7.])

In [ ]:
np.array(A/B,dtype=int)

array([0, 2, 0])

## Modulus of a Vector

The modulus of a vector or the magnitude of a vector can be determined using the Pythagorean theorem. Given the vector $A$ and its scalars denoted as $a_n$ where $n$ is the index of the scalar. So if we have:
$$A = \begin{bmatrix}1\\2\end{bmatrix}$$
We can compute the magnitude as:
$$||A|| = \sqrt{a_1^2 + a_2^2} = \sqrt{1^2 + 2^2} = \sqrt{5}$$
So if we have a matrix with more parameters such as:
$$B=\begin{bmatrix}2\\5\\-1\\0\end{bmatrix}$$
We can generalize the Pythagorean theorem to compute for the magnitude as:
$$||B|| = \sqrt{b_1^2 + b_2^2 + b_3^2 + ... +b_n^2} = \sqrt{\sum_{n=1}^{N}b_n^2}$$
And this equation is now called a Euclidian distance or the Euclidean Norm. We can implement this explicitly by for loops or using `np.linalg.norm()` to get the Euclidian Norm.

In [ ]:
A = np.array([1,2])
B = np.array([2,5,-1,0])

In [ ]:
np.linalg.norm(A)

2.23606797749979

In [ ]:
np.linalg.norm(B)

3.7416573867739413

## Vector Dot Product / Inner Product

The inner product of a vector is the sum of the products of each elements of the vectors. So given vectors $H$ and $G$ below:
$$H=\begin{bmatrix}1\\3\\6\end{bmatrix}, G = \begin{bmatrix}5\\2\\1\end{bmatrix}$$
We first take the element-wise product of the vectors:
$$H*G = \begin{bmatrix}5\\6\\6\end{bmatrix}$$
Then we take the sum of the products, making it the inner product of a vector:
$$H\cdot G = 17$$
You can solve for the inner product using an explicit function, `np.inner()` or the `@` operator.

In [ ]:
H = np.array([1,3,6])
G = np.array([5,2,1])

In [ ]:
np.inner(H,G)

17

In [ ]:
np.linalg.norm(H)

6.782329983125268

In [ ]:
np.sqrt(H@H)

6.782329983125268

## Activity

### Task 1

Make an explicit function (not using any of NumPy's preset functions) solving the modulus of a vector using the Euclidian Norm formula: 
$$||X|| = \sqrt{\sum_{n=1}^{N}x_n^2}$$
Create a program flowchart for your algorithm and explain it in your methodology. Create 6 different vectors which their element count should not be lower than 4 elements. Explain the results at the results discussion section while comparing them to the `np.linalg.norm()` function.

### Task 2

Make an explicit function (not using any of NumPy's preset functions nor the `@` operator) solving the inner product of two vectors using the inner product formula: 
$$A\cdot B = \sum_{n=1}^{N} a_n \times b_n $$
$$whereas: N = len(A) = len(B)$$
Create a program flowchart for your algorithm and explain it in your methodology. Create 5 distinct pairs vectors which their element count should not be lower than 5 elements. Explain the results at the results discussion section while comparing them to the `np.inner()` function.

### Task 3

Code the following vector operation and solve them using the given vector values

$$ ((A^2 + B^2 + C^2) * (A * (B + A*B)./C))*||A + B + C||$$
$$A = \begin{bmatrix}-0.4\\4.3\\-0.6\end{bmatrix}, B = \begin{bmatrix}-0.2\\0.2\\1\end{bmatrix}, C = \begin{bmatrix}-0.2\\2.1\\-1.5\end{bmatrix}$$

Create a program flowchart for your algorithm and explain it in your methodology. In your results, compare your answer to the expected output, visualize, and explain the resulting vector using a 3D plot.

## Conclusion guide

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. 